# Generated by cpp11: do not edit by hand

is_nested_call <- function(expr) {
  .Call(`_fastplyr_is_nested_call`, expr)
}

call_is_namespaced <- function(expr) {
  .Call(`_fastplyr_call_is_namespaced`, expr)
}

fun_ns <- function(x, rho) {
  .Call(`_fastplyr_fun_ns`, x, rho)
}

is_fn_call <- function(expr, fn, ns, rho) {
  .Call(`_fastplyr_is_fn_call`, expr, fn, ns, rho)
}

is_group_unaware_call <- function(expr, env) {
  .Call(`_fastplyr_is_group_unaware_call`, expr, env)
}

cpp_frame_addresses_equal <- function(x, y) {
  .Call(`_fastplyr_cpp_frame_addresses_equal`, x, y)
}

cpp_frame_dims <- function(x, check_rows_equal, check_cols_equal) {
  .Call(`_fastplyr_cpp_frame_dims`, x, check_rows_equal, check_cols_equal)
}

cpp_is_exotic <- function(x) {
  .Call(`_fastplyr_cpp_is_exotic`, x)
}

cpp_any_frames <- function(x) {
  .Call(`_fastplyr_cpp_any_frames`, x)
}

cpp_any_frames_exotic <- function(x) {
  .Call(`_fastplyr_cpp_any_frames_exotic`, x)
}

cpp_as_list_of_frames <- function(x) {
  .Call(`_fastplyr_cpp_as_list_of_frames`, x)
}

cpp_pluck_list_of_integers <- function(x, i, default_value) {
  .Call(`_fastplyr_cpp_pluck_list_of_integers`, x, i, default_value)
}

cpp_sorted_group_starts <- function(group_sizes, init_loc) {
  .Call(`_fastplyr_cpp_sorted_group_starts`, group_sizes, init_loc)
}

cpp_group_locs <- function(order, group_sizes) {
  .Call(`_fastplyr_cpp_group_locs`, order, group_sizes)
}

cpp_group_locs2 <- function(group_id, group_sizes) {
  .Call(`_fastplyr_cpp_group_locs2`, group_id, group_sizes)
}

cpp_vec_group_split <- function(x, locs) {
  .Call(`_fastplyr_cpp_vec_group_split`, x, locs)
}

cpp_orig_order <- function(group_id, group_sizes) {
  .Call(`_fastplyr_cpp_orig_order`, group_id, group_sizes)
}

cpp_row_id <- function(order, group_sizes, ascending) {
  .Call(`_fastplyr_cpp_row_id`, order, group_sizes, ascending)
}

cpp_which_all <- function(x) {
  .Call(`_fastplyr_cpp_which_all`, x)
}

cpp_slice_locs <- function(group_locs, locs) {
  .Call(`_fastplyr_cpp_slice_locs`, group_locs, locs)
}

cpp_consecutive_id <- function(x) {
  .Call(`_fastplyr_cpp_consecutive_id`, x)
}

cpp_grouped_run_id <- function(x, order, group_sizes) {
  .Call(`_fastplyr_cpp_grouped_run_id`, x, order, group_sizes)
}

cpp_set_list_element <- function(x, i, value) {
  .Call(`_fastplyr_cpp_set_list_element`, x, i, value)
}

cpp_fill_grouped <- function(x, order, group_sizes, fill_limit) {
  .Call(`_fastplyr_cpp_fill_grouped`, x, order, group_sizes, fill_limit)
}

cpp_df_transform_exotic <- function(x, order, as_qg) {
  .Call(`_fastplyr_cpp_df_transform_exotic`, x, order, as_qg)
}

cpp_group_starts <- function(group_id, n_groups) {
  .Call(`_fastplyr_cpp_group_starts`, group_id, n_groups)
}

cpp_group_ends <- function(group_id, n_groups) {
  .Call(`_fastplyr_cpp_group_ends`, group_id, n_groups)
}

common_length <- function(x) {
  .Call(`_fastplyr_common_length`, x)
}

cpp_group_data <- function(x) {
  .Call(`_fastplyr_cpp_group_data`, x)
}

cpp_group_keys <- function(x) {
  .Call(`_fastplyr_cpp_group_keys`, x)
}

cpp_group_vars <- function(x) {
  .Call(`_fastplyr_cpp_group_vars`, x)
}

cpp_group_rows <- function(x) {
  .Call(`_fastplyr_cpp_group_rows`, x)
}

cpp_group_size <- function(x) {
  .Call(`_fastplyr_cpp_group_size`, x)
}

cpp_ungroup <- function(data) {
  .Call(`_fastplyr_cpp_ungroup`, data)
}

cpp_group_indices <- function(rows, size) {
  .Call(`_fastplyr_cpp_group_indices`, rows, size)
}

cpp_group_by_drop_default <- function(x) {
  .Call(`_fastplyr_cpp_group_by_drop_default`, x)
}

cpp_group_by_order_default <- function(x) {
  .Call(`_fastplyr_cpp_group_by_order_default`, x)
}

cpp_group_id <- function(x) {
  .Call(`_fastplyr_cpp_group_id`, x)
}

is_data_pronoun_call <- function(expr, env) {
  .Call(`_fastplyr_is_data_pronoun_call`, expr, env)
}

all_call_names <- function(data, expr, env) {
  .Call(`_fastplyr_all_call_names`, data, expr, env)
}

cpp_quo_data_vars <- function(quos, data) {
  .Call(`_fastplyr_cpp_quo_data_vars`, quos, data)
}

cpp_quos_drop_null <- function(quos) {
  .Call(`_fastplyr_cpp_quos_drop_null`, quos)
}

cpp_any_quo_contains_dplyr_mask_call <- function(quos) {
  .Call(`_fastplyr_cpp_any_quo_contains_dplyr_mask_call`, quos)
}

cpp_eval_all_tidy <- function(quos, mask) {
  .Call(`_fastplyr_cpp_eval_all_tidy`, quos, mask)
}

cpp_list_tidy <- function(quos) {
  .Call(`_fastplyr_cpp_list_tidy`, quos)
}

cpp_unlist_group_locs <- function(x, group_sizes) {
  .Call(`_fastplyr_cpp_unlist_group_locs`, x, group_sizes)
}

cpp_group_id_sorted <- function(x) {
  .Call(`_fastplyr_cpp_group_id_sorted`, x)
}

transpose_eval_results <- function(x) {
  .Call(`_fastplyr_transpose_eval_results`, x)
}

recycle_eval_results <- function(x) {
  .Call(`_fastplyr_recycle_eval_results`, x)
}

cpp_grouped_eval_tidy <- function(data, quos, recycle, add_groups) {
  .Call(`_fastplyr_cpp_grouped_eval_tidy`, data, quos, recycle, add_groups)
}

cpp_grouped_eval_summarise <- function(data, quos) {
  .Call(`_fastplyr_cpp_grouped_eval_summarise`, data, quos)
}

cpp_grouped_eval_mutate <- function(data, quos) {
  .Call(`_fastplyr_cpp_grouped_eval_mutate`, data, quos)
}

cpp_nest_split <- function(data, drop, order) {
  .Call(`_fastplyr_cpp_nest_split`, data, drop, order)
}

cpp_group_split <- function(data) {
  .Call(`_fastplyr_cpp_group_split`, data)
}

cpp_grouped_df_as_grp <- function(data) {
  .Call(`_fastplyr_cpp_grouped_df_as_grp`, data)
}
