# Generated by cpp11: do not edit by hand

cpp_address_equal <- function(x, y) {
  .Call(`_fastplyr_cpp_address_equal`, x, y)
}

cpp_nrows <- function(x) {
  .Call(`_fastplyr_cpp_nrows`, x)
}

cpp_list_subset <- function(x, ptype, i, default_value) {
  .Call(`_fastplyr_cpp_list_subset`, x, ptype, i, default_value)
}

cpp_sorted_group_starts <- function(group_sizes, init_loc) {
  .Call(`_fastplyr_cpp_sorted_group_starts`, group_sizes, init_loc)
}

is_s3_atomic <- function(x) {
  .Call(`_fastplyr_is_s3_atomic`, x)
}

cpp_group_locs <- function(order, group_sizes) {
  .Call(`_fastplyr_cpp_group_locs`, order, group_sizes)
}

cpp_row_id <- function(order, group_sizes, ascending) {
  .Call(`_fastplyr_cpp_row_id`, order, group_sizes, ascending)
}

cpp_reduce_logicals <- function(x) {
  .Call(`_fastplyr_cpp_reduce_logicals`, x)
}

cpp_df_group_indices <- function(rows, size) {
  .Call(`_fastplyr_cpp_df_group_indices`, rows, size)
}

cpp_slice_locs <- function(group_locs, locs) {
  .Call(`_fastplyr_cpp_slice_locs`, group_locs, locs)
}
