# Generated by cpp11: do not edit by hand

cpp_frame_addresses_equal <- function(x, y) {
  .Call(`_fastplyr_cpp_frame_addresses_equal`, x, y)
}

cpp_frame_dims <- function(x, check_rows_equal, check_cols_equal) {
  .Call(`_fastplyr_cpp_frame_dims`, x, check_rows_equal, check_cols_equal)
}

cpp_is_exotic <- function(x) {
  .Call(`_fastplyr_cpp_is_exotic`, x)
}

cpp_any_frames <- function(x) {
  .Call(`_fastplyr_cpp_any_frames`, x)
}

cpp_any_frames_exotic <- function(x) {
  .Call(`_fastplyr_cpp_any_frames_exotic`, x)
}

cpp_as_list_of_frames <- function(x) {
  .Call(`_fastplyr_cpp_as_list_of_frames`, x)
}

cpp_list_subset <- function(x, ptype, i, default_value) {
  .Call(`_fastplyr_cpp_list_subset`, x, ptype, i, default_value)
}

cpp_sorted_group_starts <- function(group_sizes, init_loc) {
  .Call(`_fastplyr_cpp_sorted_group_starts`, group_sizes, init_loc)
}

cpp_group_locs <- function(order, group_sizes) {
  .Call(`_fastplyr_cpp_group_locs`, order, group_sizes)
}

cpp_row_id <- function(order, group_sizes, ascending) {
  .Call(`_fastplyr_cpp_row_id`, order, group_sizes, ascending)
}

cpp_which_all <- function(x) {
  .Call(`_fastplyr_cpp_which_all`, x)
}

cpp_df_group_indices <- function(rows, size) {
  .Call(`_fastplyr_cpp_df_group_indices`, rows, size)
}

cpp_slice_locs <- function(group_locs, locs) {
  .Call(`_fastplyr_cpp_slice_locs`, group_locs, locs)
}

cpp_consecutive_id <- function(x) {
  .Call(`_fastplyr_cpp_consecutive_id`, x)
}

cpp_grouped_run_id <- function(x, order, group_sizes) {
  .Call(`_fastplyr_cpp_grouped_run_id`, x, order, group_sizes)
}

cpp_set_list_element <- function(x, i, value) {
  .Call(`_fastplyr_cpp_set_list_element`, x, i, value)
}

cpp_fill_grouped <- function(x, order, group_sizes, fill_limit) {
  .Call(`_fastplyr_cpp_fill_grouped`, x, order, group_sizes, fill_limit)
}

cpp_unlist_group_locs <- function(x, group_sizes) {
  .Call(`_fastplyr_cpp_unlist_group_locs`, x, group_sizes)
}

cpp_df_transform_exotic <- function(x, order, as_qg) {
  .Call(`_fastplyr_cpp_df_transform_exotic`, x, order, as_qg)
}

cpp_get <- function(sym, rho) {
  .Call(`_fastplyr_cpp_get`, sym, rho)
}

cpp_is_call <- function(expr, ns) {
  .Call(`_fastplyr_cpp_is_call`, expr, ns)
}

cpp_call_contains_ns <- function(expr, ns, rho) {
  .Call(`_fastplyr_cpp_call_contains_ns`, expr, ns, rho)
}

cpp_any_quo_contains_ns <- function(quos, ns) {
  .Call(`_fastplyr_cpp_any_quo_contains_ns`, quos, ns)
}

cpp_unnest_expr <- function(expr) {
  .Call(`_fastplyr_cpp_unnest_expr`, expr)
}

all_call_names <- function(expr) {
  .Call(`_fastplyr_all_call_names`, expr)
}

cpp_quos_adjust_across <- function(quos) {
  .Call(`_fastplyr_cpp_quos_adjust_across`, quos)
}

get_mask_top_env <- function(mask) {
  .Call(`_fastplyr_get_mask_top_env`, mask)
}

cpp_eval_tidy <- function(quo, mask) {
  .Call(`_fastplyr_cpp_eval_tidy`, quo, mask)
}

cpp_eval_all_tidy <- function(quos, mask) {
  .Call(`_fastplyr_cpp_eval_all_tidy`, quos, mask)
}

new_bare_data_mask <- function() {
  .Call(`_fastplyr_new_bare_data_mask`)
}

cpp_list_tidy <- function(quos, keep_null) {
  .Call(`_fastplyr_cpp_list_tidy`, quos, keep_null)
}

get_group_data <- function(x) {
  .Call(`_fastplyr_get_group_data`, x)
}

cpp_grouped_eval_mutate <- function(data, quos) {
  .Call(`_fastplyr_cpp_grouped_eval_mutate`, data, quos)
}

cpp_grouped_eval_mutate2 <- function(data, quos) {
  .Call(`_fastplyr_cpp_grouped_eval_mutate2`, data, quos)
}

cpp_grouped_eval_tidy <- function(data, quos, as_df, check_size) {
  .Call(`_fastplyr_cpp_grouped_eval_tidy`, data, quos, as_df, check_size)
}

cpp_grouped_eval_tidy2 <- function(group_data, data, quos, as_df, check_size) {
  .Call(`_fastplyr_cpp_grouped_eval_tidy2`, group_data, data, quos, as_df, check_size)
}

cpp_group_split <- function(data, drop, order) {
  .Call(`_fastplyr_cpp_group_split`, data, drop, order)
}
